# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIDesign
   pod 'R.swift' # R.swift for managing resources
  target 'UIDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIDesignUITests' do
    # Pods for testing
  end

end
